### ISSUE TITLE
Get firmware information unsafe value

### ISSUE THREAD

**Issue by Ekristoffe** [aromajoin/controller-http-api#5]
Hello,
Get firmware information will return unsafe value when there is no internet connection available.
In that case, a random value is assigned to the "latest" key.
If possible an empty string or a predefined value should be returned.
(Json parser may crash depending on the returned value)

**Comment by hanhdt** [comment]
Thanks for your suggestion @Ekristoffe.
I'm on this issue.

**Comment by hanhdt** [comment]
Hi @Ekristoffe,

I just wanted to notify you about this issue which had been updated in the latest firmware version 2.0.4.
You can install it via OTA update.

**Comment by Ekristoffe** [comment]
Fixed in 2.0.4
(Ps do you have any release note somewhere ?)

**Comment by hanhdt** [comment]
Thanks for reviewing.
We had release notes but it's not in a public repo.
