### ISSUE TITLE
API not up to date.

### ISSUE THREAD

**Issue by Ekristoffe** [aromajoin/controller-http-api#6]
It seem the API have changed for the Firmware version 2.x.x
here is the valid request:

Request body:

```
{
    "channels": [number, ...], // The cartridge number. Range: 1 ~ 6
    "intensities": [number, ...], // The cartridge intensity as a percentage. Range: 0 ~ 100
    "durations": [number, ...], // Diffusion time in milliseconds. Range: 0 ~ 10000
    "booster": boolean // Set to true to activate the Aroma Shooter's booster fan. Default value is false.
}
```

For example:

```json
{
    "channels": [1,3,5],
    "intensities": [100,50,25],
    "durations": [1000,2000,3000],
    "booster": true
}
```

**Comment by hanhdt** [comment]
Hi @Ekristoffe,
Thanks for your reporting the issue.
We are sorry for the API documentation is not up to date.

I updated the documentation for the latest firmware version.
https://github.com/aromajoin/controller-http-api#example-requests
